ALTER TABLE users
DROP COLUMN google_id VARCHAR(255),
DROP COLUMN name VARCHAR(255),
DROP COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE users
DROP CONSTRAINT users_google_id_unique UNIQUE (google_id);